plugins {
	id 'fabric-loom' version '1.7-SNAPSHOT'
}

archivesBaseName = mod_name
version = "${mod_version}-mc${mc_version}"
group = project.maven_group

if (build_number != 'undefined') {
	version += "+build.${build_number}"
}

loom {
	mods {
		"scbt" {
			sourceSet sourceSets.main
		}
	}
	accessWidenerPath = file("src/main/resources/scbt.accesswidener")
}

repositories {

}

dependencies {
	minecraft "com.mojang:minecraft:${mc_version}"
	mappings "net.fabricmc:yarn:${yarn_version}:v2"
	modImplementation "net.fabricmc:fabric-loader:${loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${fapi_version}+${mc_version}"
	// Nullable修复
	modImplementation "com.google.code.findbugs:jsr305:3.0.2"
}

processResources {
	inputs.property "version", mod_version

	filesMatching("fabric.mod.json") {
		expand "version": mod_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${mod_name}"}
	}
}