plugins {
	id('net.fabricmc.fabric-loom').version("${loom_version}").apply(false)
	id('net.fabricmc.fabric-loom-remap').version("${loom_version}").apply(false)
	id('com.replaymod.preprocess').version("${preprocessor_version}")
}

preprocess {
	strictExtraMappings = false

	def mc12101_fabric = createNode("1.21.1-fabric", 1_21_01, "mojang")
	def mc12102_fabric = createNode("1.21.2-fabric", 1_21_02, "mojang")
	def mc12105_fabric = createNode("1.21.5-fabric", 1_21_05, "mojang")
	def mc12109_fabric = createNode("1.21.9-fabric", 1_21_09, "mojang")
	def mc12111_fabric = createNode("1.21.11-fabric", 1_21_11, "mojang")

	mc12101_fabric.link(mc12102_fabric, null)
	mc12102_fabric.link(mc12105_fabric, null)
	mc12105_fabric.link(mc12109_fabric, null)
	mc12109_fabric.link(mc12111_fabric, null)

	for (final def node in getNodes()) {
		findProject(node.project).ext.mcVersion = node.mcVersion
	}
}

ext {
	File localPropsFile = file("${rootDir}/local.properties")

	if (localPropsFile.exists()) {
		Properties p = new Properties()
		p.load(new FileInputStream(localPropsFile))
		p.each { key, value ->
			ext[key as String] = value
		}
	}
}
