# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
mc_version=1.21.4
yarn_version=8
loader_version=0.16.10
fapi_version=0.114.3

# Mod Properties
mod_version = 2.1.0
maven_group = scoreboard-tools
mod_name = ScoreboardTools

build_number = undefined
