name: Development Build

on: [push]

jobs:
  properties:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.show.outputs.branches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show branches
        id: show
        run: |

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set build number
        run: sed -i "s/undefined/$GITHUB_RUN_NUMBER/g" gradle.properties
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts for ${{ github.sha }}
          path: build/libs/
